// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDkwOrbe68alfFJsruNjf3Y8t1HSqp944',
    appId: '1:963870239540:android:c5f73ca4b474a213e05361',
    messagingSenderId: '963870239540',
    projectId: 'gym-easy-b26b5',
    storageBucket: 'gym-easy-b26b5.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdcgikjg0AXs0OXKF0SIejI49adgGNajs',
    appId: '1:963870239540:web:75f0dac229c6380de05361',
    messagingSenderId: '963870239540',
    projectId: 'gym-easy-b26b5',
    authDomain: 'gym-easy-b26b5.firebaseapp.com',
    storageBucket: 'gym-easy-b26b5.firebasestorage.app',
    measurementId: 'G-VJK5TXWWR1',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFHJJssKT5v_pIy2OtSZvEa5dsJ1WdDDM',
    appId: '1:963870239540:ios:85011acd1425adfde05361',
    messagingSenderId: '963870239540',
    projectId: 'gym-easy-b26b5',
    storageBucket: 'gym-easy-b26b5.firebasestorage.app',
    iosBundleId: 'y',
  );

}